### ISSUE TITLE
Checklist Paper Review - Due 

### ISSUE THREAD

**Issue by acatejr** [cloudmesh-community/hid-sp18-505#32]
- [ ] Although I use the term paper. It is best not to use phrases such as "In this paper e show ..." Instead, say "We show ..." It is unimportant if this is a paper, in fact, if we were to decide to put it in a book, we have a section instead of a paper, so the term paper should never be used.

 

-[ ] A 2 page paper does not need an outline such as in Section xyz we do this. In Section klm we do that , .....
The paper is just to short for this. Longer papers could benefit from it, but so far none of the 2 page pagers need it.
-[ ] c) Conclusion. The term "We showed in this paper ... " must be avoided in the conclusion. The conclusion or summary is not about what you have shown in the paper, but what your technology is about. I have read several conclusions that summarized the section outline of the paper but did not tell me about the actual technology that was reported about. 
-[ ] d) please remember that you can not use the word "I". This is not an experience report, this is a formal technical paper about a technology.
- [ ] e)  the use of a and the seems unclear to some students.
- [ ] f) The handbook has a list of checkboxes. Why not print them out or copy them to your github issues and go through them and check them. This way you are reminded about how to improve your paper.
